name: 'Build & Deployment'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker Image
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}
          build-args: |
            NODE_ENV=production
            NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}

      # Deploy to CapRover
      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ vars.CAPROVER_SERVER }}"
          app: "${{ vars.APP_NAME }}"
          token: "${{ secrets.CAPROVER_APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}

      - name: send telegram message
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🤖 *[OTFusion main-site]*
            🧾 *Status: ${{ job.status }}*
            #️⃣ Run # ${{github.run_number}}. Event type: *${{ github.event_name }}*
            🤡 Developer: *${{github.actor}}*
            🔗 Href: https://github.com/${{github.repository}}

            ✨ See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          format: markdown
          disable_web_page_preview: "True"